### ISSUE TITLE
Compile error: cannot infer type of the type parameter `C` declared on the method `constraints`

### ISSUE THREAD

**Issue by nervous-inhuman** [dpbriggs/borgtui#1]
Currently, the compiling fails on the following error:

```

   Compiling borgtui v0.4.4 (/home/foobar/.cargo/git/checkouts/borgtui-680cbb423aeb18d9/4abbe8c)
error[E0283]: type annotations needed
    --> src/borgtui.rs:1409:14
     |
1409 |             .constraints(backup_constraints.as_ref())
     |              ^^^^^^^^^^^                    ------ type must be known at this point
     |              |
     |              cannot infer type of the type parameter `C` declared on the method `constraints`
     |
     = note: multiple `impl`s satisfying `Vec<Constraint>: AsRef<_>` found in the `alloc` crate:
             - impl<T, A> AsRef<Vec<T, A>> for Vec<T, A>
               where A: Allocator;
             - impl<T, A> AsRef<[T]> for Vec<T, A>
               where A: Allocator;
help: consider specifying the generic argument
     |
1409 |             .constraints::<&T>(backup_constraints.as_ref())
     |                         ++++++

error[E0283]: type annotations needed
    --> src/borgtui.rs:1496:14
     |
1496 |             .constraints(backup_constraints.as_ref())
     |              ^^^^^^^^^^^                    ------ type must be known at this point
     |              |
     |              cannot infer type of the type parameter `C` declared on the method `constraints`
     |
     = note: multiple `impl`s satisfying `Vec<Constraint>: AsRef<_>` found in the `alloc` crate:
             - impl<T, A> AsRef<Vec<T, A>> for Vec<T, A>
               where A: Allocator;
             - impl<T, A> AsRef<[T]> for Vec<T, A>
               where A: Allocator;
help: consider specifying the generic argument
     |
1496 |             .constraints::<&T>(backup_constraints.as_ref())
     |                         ++++++

For more information about this error, try `rustc --explain E0283`.
error: could not compile `borgtui` (bin "borgtui") due to 2 previous errors
error: failed to compile `borgtui v0.4.4 (https://github.com/dpbriggs/borgtui.git#4abbe8c3)`, intermediate artifacts can be found at `/tmp/cargo-installv0s8ul`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by dpbriggs** [comment]
Hmm it seems to compile fine on my system. What version of rust are you using? It works on stable 1.75 on my system. I ran into a similar error before when upgrading my rustc version but pushed 2851db95 to fix that.
